theme: jekyll-theme-minimal
title: Brady Rothrock's Portfolio
description: This is a portfolio of some work I've completed in the past.
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
